# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/fairphone/FP5/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),FP5)

$(call add-radio-file-sha1-checked,radio/bluetooth.img,ab593e223bd31cb1e76c3613afb396e4ef370874)
$(call add-radio-file-sha1-checked,radio/modem.img,db5c36200be677f980cf32b41900090ac8e5fcf2)
$(call add-radio-file-sha1-checked,radio/abl.img,1fa1968bee324679fc3add326d91f701a560c1f3)
$(call add-radio-file-sha1-checked,radio/aop.img,79a9d51647a6848fe02603537c6c9d7fc1248f11)
$(call add-radio-file-sha1-checked,radio/cpucp.img,2fe68729dcb3ca104af29d2d5a47c9efaee7af6a)
$(call add-radio-file-sha1-checked,radio/devcfg.img,054b573b813bbcaebf4f672354e9ed8f17d73230)
$(call add-radio-file-sha1-checked,radio/dsp.img,a84e42ca638142791745acb99a0ba8e4dfc5372a)
$(call add-radio-file-sha1-checked,radio/featenabler.img,443f72f2a1ee06afb80a0221a98b8324dbf1d4d2)
$(call add-radio-file-sha1-checked,radio/hyp.img,57ad1d59ac0e58a5036c5cd84cbe326c32d536ab)
$(call add-radio-file-sha1-checked,radio/imagefv.img,4e9663764f3488c5006872d5cbab4814b572d179)
$(call add-radio-file-sha1-checked,radio/keymaster.img,06553e213a8218e7d5e8af5247a4c0dff8aaa597)
$(call add-radio-file-sha1-checked,radio/multiimgoem.img,811916468d8d5b1b6cb3f3a695b52d0dd7edb2fa)
$(call add-radio-file-sha1-checked,radio/qupfw.img,79f19c07722d357da8e1879275e621a74768b168)
$(call add-radio-file-sha1-checked,radio/shrm.img,d24de741245a343b1e6626e6eea34ca34af9c851)
$(call add-radio-file-sha1-checked,radio/studybk.img,9d3167db931410f9e4d9dbf1a2c4effd17189b3d)
$(call add-radio-file-sha1-checked,radio/tz.img,59d37b77f7924ffeca59564de3ca17c912986fa2)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,e93d7af3dcd73ee116804019972bcfa89ad1c0e4)
$(call add-radio-file-sha1-checked,radio/xbl.img,ce9d9e11f56a02b065d80cdb91a6291aca012f7c)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,323e4be05134a2d1ad1e17bff3f54b9256e885b2)

endif
