# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/fairphone/FP5/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),FP5)

$(call add-radio-file-sha1-checked,radio/bluetooth.img,2ec709e0a8c417145b9f6a535423b129b27f91ce)
$(call add-radio-file-sha1-checked,radio/modem.img,6469e017645c912162d983b6d2ffe2e6822a42ee)
$(call add-radio-file-sha1-checked,radio/abl.img,f6bc37bd8e8d89235cb71095409549891380a9ad)
$(call add-radio-file-sha1-checked,radio/aop.img,ae706e00010f84834df4de4ec45da9bba6f2d5da)
$(call add-radio-file-sha1-checked,radio/cpucp.img,9e8cb6f643a85b3dacf8ac678c2764cb59e62e66)
$(call add-radio-file-sha1-checked,radio/devcfg.img,127dc175d98d09acc352d61c3037431076b9e609)
$(call add-radio-file-sha1-checked,radio/dsp.img,5b392f0228e7995894da3081c36442ba5a51394a)
$(call add-radio-file-sha1-checked,radio/featenabler.img,cb7ee1b3f4825e26f41e97cfdd68a7bbf5aff1d5)
$(call add-radio-file-sha1-checked,radio/hyp.img,aed32562a3f523809e2764fa32658910557764fd)
$(call add-radio-file-sha1-checked,radio/imagefv.img,1d32581f3f55dd333a462af4e97189f966d13209)
$(call add-radio-file-sha1-checked,radio/keymaster.img,224c0f5a106448b6c3843335dabdd507e8fadb08)
$(call add-radio-file-sha1-checked,radio/multiimgoem.img,4ed3ce264fc94706330bc691fbac069620309c8a)
$(call add-radio-file-sha1-checked,radio/qupfw.img,2c575fc28d695ca9d094f029c79ee83416b1cd08)
$(call add-radio-file-sha1-checked,radio/shrm.img,2b7366c9717314b70a61ab3e8b46d61c9a753c90)
$(call add-radio-file-sha1-checked,radio/studybk.img,1e58925ca1ea898c3677ec48a6a78513f278a168)
$(call add-radio-file-sha1-checked,radio/tz.img,a38614a5f5bd877c381aaa7c5adb43678f5b3d7d)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,e73d827c9951e6022dda55cdbaa6c7dd9022190e)
$(call add-radio-file-sha1-checked,radio/xbl.img,5c1996e330c38c5e8b67e955018cbc4e18d5587a)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,1db76a98598112b69a1c17ce9ce639809d2bf9d9)

endif
